### ISSUE TITLE
Improve wind generation modeling

### ISSUE THREAD

**Issue by lshaver** [ucsusa/pypsa-illinois#14]
The model currently uses wind turbine assumptions, based on the [GE 2.75-103 wind turbine](https://en.wind-turbine-models.com/turbines/747-ge-general-electric-ge-2.75-103) for all wind generation. A more generic and/or diverse set of modeling assumptions should be used.

**Comment by samgdotson** [comment]
@lshaver I agree it could be improved but I don't think it can be effectively addressed at this time. I'm going to close the issue for now, it may be reopened later.
